### ISSUE TITLE
Typographic change: Make "H6" 14 px

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#112]
**Design change**

**H6**
- Font-size 14
- Font-weight Regular
- Line-height 20
- Color #333333

**Reason**
To be able to differentiate between a primary and secondary headline in a supporting area/box.

**Description**
 https://designlibrary.sebgroup.com/visual-identity/typography/ 

**Examples**
![image](https://user-images.githubusercontent.com/45568194/55565493-35723280-56fa-11e9-93db-30965d852554.png)

Thank you!
/Ulrika

**Comment by hjalmers** [comment]
It's 14 px (0.875 rem) already:D However it's no font weight regular as in the example above, which it probably shouldn't be. However the "lighter" version can easily be achieved by adding `font-weight-regular` like this:

```html
<h6 class="font-weight-regular">Regular font weight</h6>
```
