### ISSUE TITLE
_forms.scss compilation error

### ISSUE THREAD

**Issue by rvinalon** [sebgroup/bootstrap#140]
Our team is an having issue compiling seb bootstrap when importing in our angular application. 
"@sebgroup/bootstrap": "^3.4.1"

![image](https://user-images.githubusercontent.com/25241044/61863536-5b6a4f80-af02-11e9-8c9c-8d3f299a55cd.png)

**Comment by hjalmers** [comment]
Duplicate #123, have you tried version 3.4.2 @rvinalon were this error should have been solved? Please note that there’s a [version 4.0.0](https://github.com/sebgroup/bootstrap/releases/tag/v4.0.0) as well that was released last week, no big breaking change so you should be fine updating to it:)
