### ISSUE TITLE
Tab design (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#149]
### Design update 2019-10-25
![image](https://user-images.githubusercontent.com/45568194/67577849-923e4480-f741-11e9-8353-90f5d9c9d2a4.png)

The design of the tab component has been adjusted:
- States for hover and focused have been updated
- Overflow tab is left-aligned (used to be right-aligned)

**Mobile version**
- The arrow is moved into the tab and a tiny line is added to look like a tab
- Instruction is clarified: Feel free to display more than one tab in a mobile. If there are too many tabs for the width that calls for an overflow menu, then only the active tab is presented (with arrow).

**See the specification to get the correct details:**
https://designlibrary.sebgroup.com/components/tab/#specification

**Original discussion**
https://github.com/sebgroup/design-library/issues/66

Thank you @TheresaHedlund for working on this!

Any feedback? Do contact designlibrary@seb.se
Ulrika,
Design Management

**Comment by hjalmers** [comment]
Just to keep track of why this was marked as won't fix.
This library only contains css i.e. only markup and style rules and it's with current technology not possible to achieve the desired behavior with tabs turning into dropdowns on mobile devices. The way to go would be to switch from using tabs to a dropdown for mobile devices, something that requires javascript and additional logic.
