### ISSUE TITLE
Badge (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#200]
### Design update 2020-01-13

**What is this?**
This component calls attention to a status/tag/category.
![image](https://user-images.githubusercontent.com/45568194/72283689-95114d00-363f-11ea-952d-556b86833a3e.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/badge/

**Component identifier**
component-badge

Thank you!
/Ulrika

**Comment by hjalmers** [comment]
Great! It’s actually already implemented but will make sure there are examples of how to use it:D
