### ISSUE TITLE
Change name of Alternative button to Button link

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#213]
### Change
The button **Button link** used to be called Alternative button.
![image](https://user-images.githubusercontent.com/45568194/73255582-abcbae00-41c0-11ea-847c-77eba28105a8.png)

### Reason
The name Button link says what it is.

Feel free to update this in your frameworks so that we use the same language on components. If this is not relevant to you, please close the issue with a comment. Thank you!

/Ulrika,
Design Management team

**Comment by hjalmers** [comment]
Closing as this already implemented in bootstrap:)
