### ISSUE TITLE
Contextual help button (new-ish)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#270]
### Design decision 2020-03-18
![image](https://user-images.githubusercontent.com/45568194/77181545-c9840800-6acb-11ea-8243-4a2e24459ab1.png)
**What is this**
A button that will present an explanation to a problem/question, with a tool tip or a slide-out modal.

**Details**
https://designlibrary.sebgroup.com/components/contextual-help-button/#specification

**Reason**
There are a few versions of this (different designs, "the info-i", etc) but it is now agreed that this is the way it should look and act. Less confusion!

**Component identifier**
component-contextual-help-button

If this issue is not relevant to you, please comment and close.
Thank you! :)
/Ulrika

**Comment by hjalmers** [comment]
This is just a icon that you can click on and either show a tooltip, popover, slide-out or something else so it's not going to be a new component in bootstrap. Examples and more info can be found here: https://sebgroup.github.io/bootstrap/tooltips
