### ISSUE TITLE
Sync gray colors 

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/bootstrap#274]
See https://github.com/sebgroup/design-library/issues/67#issuecomment-559711848

**Comment by JessiNygrenWalhed** [comment]
This is what we decided today. Design Library will make changes on Grey 1-7 hex. Bootstrap will change the hex on 800 & 900. The naming will also change to 100-900 to match Bootstrap. 

These are the correct grey colours:
gray-100: #f8f8f8
gray-200: #e9e9e9
gray-300: #dedede
gray-400: #cecece
gray-500: #adadad
gray-600: #868686
gray-700: #494949 
gray-800: #33333
gray-900: #1a1a1a
![The Grey squares update](https://user-images.githubusercontent.com/45595414/77328825-638ebf00-6d1d-11ea-805f-450c9b3cc6f5.png)
