### ISSUE TITLE
@functions are not compiled with sass-loader@v8

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/bootstrap#302]
### Description
After upgrading to `sass-loader@v8`, I started running into issues where @functions are not being compiled. I usually import variables from:
```scss
@import "~@sebgroup/bootstrap/scss/variables";
```
Some of the variables like `$accordion-icon` is calculated using custom functions like `str-replace`, `str-length` and `str-slice`. These functions are imported in the variables folder at lines (**536**-**537**):
```scss
@import "bootstrap-core/functions";
@import "bootstrap-core/variables";
```

In`sass-loader@v7` it shows like this:
![image](https://user-images.githubusercontent.com/10633734/79183246-80fa0900-7e43-11ea-9f49-f679edda4f5d.png)

But in `sass-loader@v8` it started showing like this:
![image](https://user-images.githubusercontent.com/10633734/79183203-6889ee80-7e43-11ea-9cf4-17502f9e1f63.png)

### Workaround
The only workaround I found is to import the functions right before the variables ignoring the fact that it's already been imported inside the variables;
```scss
@import "~@sebgroup/bootstrap/scss/bootstrap-core/functions";
@import "~@sebgroup/bootstrap/scss/variables";
```

**Comment by hjalmers** [comment]
What happens if you import core instead of variables?

```scss
@import "~@sebgroup/bootstrap/scss/core";
```

**Comment by yousifalraheem** [comment]
Yeah, it does work, I don't know why doesn't work with only variables file as it used it before. The import for functions is already inside variables. Closing this issue for now. Thanks
