### ISSUE TITLE
Spinners should be transparent

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/bootstrap#306]
## Description 

When spinners get rendered on top of other elements or non-background containers it will have a white artifact while it should be completely transparent.

On white background:
![2](https://user-images.githubusercontent.com/10633734/79424942-8c8c3200-7ff3-11ea-9da8-62c1c5d5ce6e.gif)

On none white background:
![1](https://user-images.githubusercontent.com/10633734/79425214-f3115000-7ff3-11ea-829e-99d2cf5a43e8.gif)

## Additional information
I found a potential fix of implementing a circle without fill [here](http://jsfiddle.net/hashem/u78bQ/). But I didn't find any instructions on how to contribute to this project. (`CONTRIBUTING.md`).

## Unrelated
On separate regard, you have 4 sizes for spinners `sm`, `md`, `lg`, and another size that is not defined with any keyword (between `sm` and `md`. Usually, in Bootstrap they would use something like `xs`, `sm`, `md`, `lg` and having `md` as default. In case you don't pass any size class, it will use `md` style. I was trying to create size options in React Loader component and didn't know what to call it:
```typescript
export type LoaderSizes = "sm" | "unnamed-size" | "md" | "lg";
```

Do you have plans of changing these size classes or should I just call it something like `default`?

**Comment by hjalmers** [comment]
This when by my radar completely, but yes I agree. In a perfect world the background should be transparent  but it's not possible without adding another element to the markup or changing the appearance of the spinner. This component was and still is in some ways a bit experimental and it was never ment to be put on top of other content other than cards (white background) or straight in the body (light grey). It supports those two cases currently and it would be fairly easy to make it possible to use any fixed background color, however not images or other things.

### Why just one element?
Why just one element one might ask, well first of all we've changed the design a couple of times already and it's most likely going to change again. The loader is used quite frequently in different applications and if the presentation is dependent on a complex markup structure it's going to be hard to change the spinner purely using css, most apps would then have to update their markup. This could or course be mitigated by introducing a breaking change and change the markup from:

```html
<div class="spinner"></div>
```
To something like:
```html
<div class="spinner>
  <div class="spinner-inner"></div>
</div>

Which would allow use more complex designs. We could even make use of the `span` element which most teams have added now anyways although it's not need for the sake of the design.

i.e

```

<div class="spinner spinner-lg" role="status">
   <span class="sr-only">Loading...</span>
</div>
```


### Why not make it a web component?
It probably should be and will be at some point, however most of our apps show this spinner before any other content has loaded including javascript resources. We need to have a light weight version using minimal markup and css to show this spinner before other resources have loaded.

I'm open to suggestions though, and I think we should clarify in design library when loaders should be used and how. I've seen a lot of examples where this spinner has been placed on top of tables etc. when skeleton loaders would be a better and more correct way to go.

Like I said initially this component was added as an experimental thing and it probably needs a bit more love in terms of design. It was pretty fun that just a short while after we added this component, bootstrap actually added a component called spinner: https://getbootstrap.com/docs/4.4/components/spinners/ personally I'd like if we could switch to their markup to stay in line with bootstrap. 

I agree regarding the sizes too.

What do you think of the following actions?

- [ ] Revisit spinner design with CX 
- [ ] Use markup from bootstrap?
- [ ] Use size structure from bootstrap?

**Comment by hjalmers** [comment]
A "temporary" fix or improvement would be to tell the spinner component to inherit the background color which would make it possible to do this:

```html
<div class="spinner spinner-sm bg-dark" role="status">
          <span class="sr-only">Loading...</span>
</div>
```
![image](https://user-images.githubusercontent.com/1632755/83233376-e48b8c00-a18e-11ea-8691-a4c1b439ff97.png)


```html
<div class="spinner spinner-sm bg-warning" role="status">
          <span class="sr-only">Loading...</span>
</div>
```
![image](https://user-images.githubusercontent.com/1632755/83233271-c2920980-a18e-11ea-9052-6a93a5561525.png)

Etc. 

By default it should also use the color of it's parent so the if it's in a container or something else with `bg-primary` for example it would be blue.
