### ISSUE TITLE
Transparent background for Secondary button

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#307]
### Design decision 2020-04-15
**Change**
The secondary button needs a transparent background. It used to be white. Some frameworks have already changed this, but I put it here to make sure we are consistent throughout every framework

![image](https://user-images.githubusercontent.com/45568194/79438291-a289fa80-7fd3-11ea-9a22-c6570aa8bdc4.png)

**Reason**
This button is commonly used on white or grey backgrounds and took too much focus for being a secondary button. (On any other backgrounds, colours, images, etc, ghost buttons are preferred.)

**Details** 
https://designlibrary.sebgroup.com/components/forms/button/#specification

If this issue is not relevant, please comment and close.

Thank you!
/Ulrika, Design Management

**Comment by hjalmers** [comment]
It's already transparent in Bootstrap, however the disabled state has a white background for some reason so I'll fix that at least:)
