### ISSUE TITLE
dropdown arrow animation bugs

### ISSUE THREAD

**Issue by mario-subo** [sebgroup/bootstrap#374]
![image](https://user-images.githubusercontent.com/49055952/82991881-edfee200-a030-11ea-89ac-3de7266a6adb.png)
![image](https://user-images.githubusercontent.com/49055952/82992176-5c43a480-a031-11ea-8bee-b503ce69b158.png)

The new animation for the arrow is not centered when pointing up and it does not work when the dropdown is above the button 

( not sure if this issue is in the docs only )

**Comment by hjalmers** [comment]
Thanks for creating this issue, it's actually an issue here https://github.com/sebgroup/ng-bootstrap/issues/92 (which I just created now). It's correct in this repository but the style gets overriden by ng-bootstrap right now. I've fixed it locally but haven't had time to push it yet and bump the ng-bootstrap version used by the bootstrap demo.
