### ISSUE TITLE
Accordion gets a box-shadow on focus

### ISSUE THREAD

**Issue by rasmusenhorning** [sebgroup/bootstrap#375]
When clicking an accordion button the button ends up in a focus state and since the button is of the class `btn-link` it gets a `box-shadow`. So it looks like this
![image](https://user-images.githubusercontent.com/5517172/83150840-10a9fd00-a0fc-11ea-9c62-86c713f64ce0.png)

which is probably not desirable in the case of an accordion button.

**Comment by hjalmers** [comment]
related to #367
