### ISSUE TITLE
Bootstrap/Design Library - Different margins in our modal **Slideout**

### ISSUE THREAD

**Issue by JessiNygrenWalhed** [sebgroup/bootstrap#421]
We need to change the margins in Bootstraps modal **Slideout** to be consistent. 
In DL Desktop use 32px (2 rem), Mobile 16px (1 rem). Bootstrap use 16px (1 rem) on both. 
Desktop modal in Bootstrap should change to 32 (2 rem).
😄 Agree?

**Comment by hjalmers** [comment]
Okay currently there's no margins in for the modal but I guess you're referring to the padding which has kind of similar effect i.e. the spacing between the outer borders of the modal and the content inside it?

We have a setting called reponsive gutters or at least we used to have one, that if enabled made gutters wider on bigger screens. I think if we want to have more spacing between elements on bigger screens that's probably the way to go as it would make the experience more consist and not only affect a single modal. Most elements and components in bootstrap rely on a global spacing property, the grid relies on this value too which means that grids would get wider gutters to on desktop.

Me and Panos experimented a bit with it and it looked nice but added complexity and the code grows exponentially with every breakpoint we add. We had 4 breakpoints (each with different spacing values), maybe we could give it another shot and try with 2?

Not sure if that makes sense? Of course we could just alter the slideout but then it would differ from cards, alerts, toasts other modals and components with spacing (padding).
