### ISSUE TITLE
Add example for only using precompiled CSS

### ISSUE THREAD

**Issue by jonaslalin** [sebgroup/bootstrap#53]
With additional instructions for SEB fonts.

A user might not want to use the SASS compilation step since the user has problems installing `node-sass`.

**Comment by axberg** [comment]
Any update on this? Where can I find the download of the precompiled css?

**Comment by hjalmers** [comment]
@axberg what kind of app are you building and how were you planing to use the css?

If you're using npm you can add a dependency to bootstrap in your app using:

```
npm install @sebgroup/bootstrap --save
```

You'll then find the pre-compiled and minified versions in
```
node_modules/@sebgroup/bootstrap/css/
```

Currently there are four pre-compiled files:
```
bootstrap.css
bootstrap.min.css
bootstrap-all.css
bootstrap-all.min.css
```

The difference between `bootstrap.css` and `bootstrap-all.css` is that `all` also contains styles for third party libraries like `ng-bootstrap`, `generic-table` and `ngx-toaster`.

I've created a small example on the link for the preferred way of using the pre-compiled version in a web app. Note however that the example uses as public npm cdn called unpkg and we're not allowed to use these kinds of services for production so until we have our on cdn you'd have to host the css yourself. 

[Serve css using CDN](https://stackblitz.com/edit/seb-css-cdn-example?embed=1&file=src/index.html)

The files are also available for download here: 
https://unpkg.com/@sebgroup/css/bootstrap.css
https://unpkg.com/@sebgroup/css/seb-fonts.css

The fonts aren't part of bootstrap so there's currently an issue with the path in the pre-compiled version, therefor you need to add the seb-fonts library as well (if you install bootstrap using npm you'll get the fonts too). (I'm going to create an issue for that as well)

Last but not least, I wouldn't recommend using a pre-compiled version as you´ll probably add a lot of styles and css that you won't use and with sass you can just use the parts you need. If you still want to use a pre-compiled I might suggesting compiling only the styles you need using the sass files (let me know if you need any help with that).
