### ISSUE TITLE
Cannot click on slide toggle

### ISSUE THREAD

**Issue by danTheSwedeMan** [sebgroup/bootstrap#60]
Cannot click on left side of the toggle when toggle is on which is confusing for the user and also inconsistent.

toggled off right side => is clickable
toggled off left side => is clickable
toggled on right side => is clickable
toggled on left side => NOT clickable

![image](https://user-images.githubusercontent.com/690521/48942705-f5679b80-ef20-11e8-9e79-ec26f1a704d7.png)

Suggested solution: 

Remove/change 
pointer-events: none;
in class
.custom-control-label::before

**Comment by hjalmers** [comment]
Thanks for creating an issue and even better, coming with a solution:D Would you mind creating a pull request for this? I'll add it myself otherwise since it's such a small fix:)

**Comment by danTheSwedeMan** [comment]
I Will fix it. I just have to learn how to do it first 🙂

Den fre 23 nov. 2018 17:30 skrev Robert Hjalmers <notifications@github.com>:

**Comment by hjalmers** [comment]
Let me know if you have any questions or need help:) It might be a little tricky to know where changes should be made.

**Comment by danTheSwedeMan** [comment]
yep. 

I think I found where I should do the change. But now I wonder if I should create a branch and add the one liner and then do a pull request or should I just checkin to master?

**Comment by hjalmers** [comment]
Master is locked so you have to create a pull request which should be to develop, this project also utilizes commitizen so you have to use a specific commit message to be able to commit. If you’ve made a fork or cloned the repository just run ‘npm run commit’ and you’ll be guided through the commit. We use semantic release for releases which generates a changelog automatically and determines the next version based on the commit messages. Once we’re ready to cut a new release we just merge dev into master.
