### ISSUE TITLE
latest color for background and link

### ISSUE THREAD

**Issue by kherP** [sebgroup/bootstrap#640]
According to Theresa, the latest color for bg is now #eeeeee and the one for link is now #0062BC, that means we will need to update the color for gray-100 to  #eeeeee and blue-darker to  #0062BC

**Comment by hjalmers** [comment]
Hi @kherP, yeah we haven't updated the background color yet and even though it's a small an easy change code wise it affects a lot of things. Just updating the background color would mean that things that have been built to play nice when placed against the background would have to be updated too e.g. spinners, buttons, skeleton loaders etc. that need to appear to have a transparent background. The obvious solution to this problem would off course be to update the gray-100 variable to use a different gray color. But doing so would also affect lots of other things relying on the gray-100 to be a pretty light gray color, i.e disabled would become too dark etc. it's on the my list of things to look into but I just haven't been able to prfioritize it. Background color is also determined by the shells and they can override the default by declaring `$body-bg` before importing @sebgroup/bootstrap although it will yield the same results, eg. spinners, skeleton loaders etc will not look that nice when placed against the background which then uses a different shade of gray.

Same goes for blue-darker, it used for more the link, I'm fine with other things using that color getting slightly darker though:) We also have the option to set a specific blue color just used by links, what would you prefer @kherP?

Feel free to create a pull request too:)

**Comment by kherP** [comment]
Thank you for your explanation, I guess for now, it will be the best to update the color by overriding the variables on our local projects
