### ISSUE TITLE
Low contrast between text and background colors.

### ISSUE THREAD

**Issue by valgerst** [sebgroup/bootstrap#698]
Hello,
During our accessibility testing we noticed a lot of contrast between text and background colors errors.
![InkedContrast errors_LI](https://user-images.githubusercontent.com/84859561/119689503-94064780-be51-11eb-8ff4-b4a15b56d350.jpg)
![Inkedcontrast errors2_LI](https://user-images.githubusercontent.com/84859561/119689548-9ec0dc80-be51-11eb-9332-c71e3f162323.jpg)
![Inkedcontrast errors3_LI](https://user-images.githubusercontent.com/84859561/119689587-a5e7ea80-be51-11eb-9035-4a756653478e.jpg)
Are there any plans regarding active and inactive buttons, links coloring?

Thank you,
Valentina

**Comment by hjalmers** [comment]
Hi @valgerst  and sorry for the late reply, @sebgroup/bootstrap is just a theme and relies on colors etc being declared and defined by https://designlibrary.sebgroup.com/. There are still some differences between the two and they're not always in sync. We're currently working with a new css library called green chlorophyll which will replace vanilla and bootstrap once it's ready so we probably won't do any major changes in bootstrap. It's also a bit challenging with colors and contrasts as it depends on how you use and combine things. If there's something in particular that we need/should adjust e.g. link color we will of course look into it but hopefully you should be able to migrate to green chlorophyll instead.
