### ISSUE TITLE
Date picker component

### ISSUE THREAD

**Issue by Dum6o** [sebgroup/bootstrap#774]
When?

![image](https://user-images.githubusercontent.com/47832903/127477277-e022195a-add2-432c-87ee-38b622e50148.png)

**Comment by hjalmers** [comment]
@Dum6o I haven't had time to add an updated example here but it's part of another lib (@sebgroup/ng-bootstrap) which was updated recently. It works with the latest version of angular and ng-bootstrap (which it relies on). You can view an example [here](https://sebgroup.github.io/ng-bootstrap/master/datepicker) (it has some issues with clicks inside the datepicker but it should be fairly easy to fix).
