### ISSUE TITLE
Library dont get a 100% pass with lighthouse

### ISSUE THREAD

**Issue by jermon** [sebgroup/bootstrap#811]
If you check the demo site with Goolge Lighthouse you dont get a 100% score

![bild](https://user-images.githubusercontent.com/4380334/158548413-afe8a189-c053-4914-8fa1-91cec54da41b.png)

**Comment by hjalmers** [comment]
This projected has been deprecated in favor for [Green](https://github.com/sebgroup/green) which is the new design system, please check it out 🚀
