### ISSUE TITLE
Updated height on Input Field, Drop Down, Medium Button, Segmented Control and Stepper

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#83]
**Design change 2019-01-30**

This issue was reviewed today in Design Working Group. We decided the following change:

- Form components (Input Field, Drop Down, Medium Button, Segmented Control and Stepper) all have the same height: 44 px
- This applies to both desktop and mobile

The reasoning for this is that when labels got bigger, the form components follow in size to harmonise and match. Also, the mobile click area needed to be bigger so we want them to be the same size, to simplify and have fewer options (=easier to do it right).

Discussion: https://github.com/sebgroup/design-library/issues/16

Thank you!
/Ulrika, Design Management

**Comment by hjalmers** [comment]
CSS (Cascading Styles Sheets) really have an cascading affect so the following have now been adjusted:

**Button sizes** (includes dropdown and segmented control aka button groups)
- small 32 px _(prev. 31 px)_
- default (medium) 44px _(prev. 40 px)_
- large 56px _(prev. 48px)_

**Input fields** (includes selects and stepper aka input groups)
- small 32 px _(prev. 31px)_
- default (medium) 44px _(prev. 40px)_
- large 56px _(prev. 48px)_

**Tables** (row height, to fit buttons and inputs of same size)
- default 44 px _(prev. 40px)_
- small 32 px _(prev. 28px)_

**Accordion**
- 44 px _(prev. 40px)_

**Nav items** (includes nav bar, tabs etc.)
- 44 px _(prev. 40px)_
