### ISSUE TITLE
Input field error indicator

### ISSUE THREAD

**Issue by ulde01** [sebgroup/bootstrap#94]
**Design change 2019-01-30**

This change was reviewed in Design Working Group:

- The error indicator for input fields have a 2 px line (#D81A1A) at the bottom
- No frame or shadow (as in Bootstrap)
- No error indication icon in the text field

The reasoning for changing the line from 4 px to 2 px is that the line was too hefty, especially when there were many fields lighting up at the same time. We try this for now and evaluate. Please give us feedback so we can learn in time for the next update.

![image](https://user-images.githubusercontent.com/45568194/52566363-e26eb400-2e09-11e9-94be-160702108976.png)

/Ulrika,
Design Management

Discussion: https://github.com/sebgroup/design-library/issues/13

**Comment by hjalmers** [comment]
This was solved with #84
